baseURL       = "/"
languageCode  = "en-US"
title         = "Dante De Ruwe"
theme         = "deruwe.me"

# Site Params
[params]
  brand     = "Dante De Ruwe"
  dateFormat = "02 JAN 2006"
  # Meta data
  description = "Personal website of Dante De Ruwe, a full-stack developer from Flanders, Belgium."
  author = "Dante De Ruwe"

# Banner Section
[params.banner]
enable                = true
background_image      = ""
heading               = "Dante De Ruwe"
tagline               = "FULL-STACK DEVELOPER"
primary_button        = "View my work"
primary_button_url    = "projects"
secondary_button      = "Contact me!"
secondary_button_url  = "contact"
    
[markup.goldmark.renderer]
unsafe= true


[module]
  [[module.mounts]]
    source = "node_modules/medium-zoom/dist/medium-zoom.min.js"
    target = "static/js/medium-zoom.min.js"
  [[module.mounts]] # dont't know why but this is needed
    source = "static"
    target = "static"
